local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
function pBvAHNijWXsfFwoIe(data) m=string.sub(data, 0, 55) data=data:gsub(m,'')

data = string.gsub(data, '[^'..b..'=]', '') return (data:gsub('.', function(x) if (x == '=') then return '' end local r,f='',(b:find(x)-1) for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end return r; end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x) if (#x ~= 8) then return '' end local c=0 for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end return string.char(c) end)) end


 


local b=pBvAHNijWXsfFwoIe('dFOwKYBezOaZRIYnwhobuAWSEEEpLtqAoIjubsHEyruuMzTxXSJpORBQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVphYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejAxMjM0NTY3ODkrLw==')
function wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(data) m=string.sub(data, 0, 55) data=data:gsub(m,pBvAHNijWXsfFwoIe('emRICBFBxxScQNyqalHzTMOKzVqbAPwYnugPApEUcarQXxPJLDsmfac'))

data = string.gsub(data, pBvAHNijWXsfFwoIe('SYfaPuaNWEyDatjOUBlfRQgNegsInqrhpSjHZlUJuLGxGJLcvvcnuZnW14=')..b..pBvAHNijWXsfFwoIe('uUKAxyvtIqZPOzRrjglGvupOORyEVqVtybocsBUfuffBuOWQdWdbmwmPV0='), pBvAHNijWXsfFwoIe('uDfJIMvIBKkolDAxYJvcELRIDqdtdOkxPdoEbeQazDhWQHyuJWydCHj')) return (data:gsub(pBvAHNijWXsfFwoIe('UBxaZEThvmFquWxClfxSONwpnlvEhPSeBcsLHzdsAnCZgBSixJasjlCLg=='), function(x) if (x == pBvAHNijWXsfFwoIe('RNgHfGYdccUjeVGnvBdpRQmAwdiJAVtzBrErXqGYVembdZLBwlTdPuCPQ==')) then return pBvAHNijWXsfFwoIe('oGzjFVttqbSHzYvPecqirHekOIEcPuJfxMPSwNAbBLBzyRkDIzbMeDm') end local r,f=pBvAHNijWXsfFwoIe('kFsSsarGneZhATiIFcJvMEuOpWTRUUebFBmRWEQwmWwygTejgFgOfIY'),(b:find(x)-1) for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and pBvAHNijWXsfFwoIe('SwXMYcRkluqkXCSncHIEIRWfBjTrVmBQtRMPFrMEIAoxGvhLlrMJgGIMQ==') or pBvAHNijWXsfFwoIe('lEDSDCGbReUbQXIcsdwvWNCSDuXnGAKjWdQKSEJuCBltcxxjPsVZBpMMA==')) end return r; end):gsub(pBvAHNijWXsfFwoIe('QgvZFwCHfyaTeNJNpQBXsbrJfwdGaATptnpBvIfGkhxBKuvxOzyZvOBJWQlZCVkPyVkPyVkPyVkPyVkPyVkPw=='), function(x) if (#x ~= 8) then return pBvAHNijWXsfFwoIe('kvJaPkyPNtkBwFZSkMILlBxDWOCudCtUOgcVctMXywsFLXPNwRURaWk') end local c=0 for i=1,8 do c=c+(x:sub(i,i)==pBvAHNijWXsfFwoIe('mUblHmRHqtWyndAuzVwszhZGBxRIXGsXfjbWMNEYbaPPsJGjdZEnZNIMQ==') and 2^(8-i) or 0) end return string.char(c) end)) end


 


local b=wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('lphypaFIzRDGTjCNaqQJnedHevyhlHaBlDrFEJEZqfaPmofAmwNOhoneUp1Z2duTVdReEdsQU5mZm5hSUFndWx3WlJQUWdLS2Z2ZWZPeUZzb21Tc3dkQkhNYVVZUkprbVFVSkRSRVZHUjBoSlNrdE1UVTVQVUZGU1UxUlZWbGRZV1ZwaFltTmtaV1puYUdscWEyeHRibTl3Y1hKemRIVjJkM2g1ZWpBeE1qTTBOVFkzT0Rrckx3PT0='))
function jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(data) m=string.sub(data, 0, 55) data=data:gsub(m,wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('SypSLFOdTKemdKFzaaVHzReUuiRqksswEyRhBaVMDZCSGTovxcnTTcZTm9DVWFUYXFkRkRmb1hIdmpvTEFZZlNJcW9kd0FrZ3hVSmpGeVBMR1VwSmFxT25CQ3VDeU9sQw==')))

data = string.gsub(data, wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('BBUrTYCCGPrdwKyQdqaRqTfgUTBzpNBCyPFVydXcWIUNMCBwKMebSsaZ3pPbU5OcVBtdWNqTmpoUGtEU2xOeXhkc0ZQb2h5c2RQWlFBcVFqTlVzSFhlTUxZSG9DU2Z3blcxND0='))..b..wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('TFyeaaiCqqmKhUQYiDmVDjWjDWgsyaOAytfeUxBhUUbiyPMOqVmPDjFQ0hxYWZDbk1vY2JUZFROc2lsTk9qa2ZGVlRwZk1wb0RPaGJGZ2VhRnJvT2lYbWp0SGJYVE1WSVBWMD0=')), wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('aGNeeuGHgvBCiZMNlPoRgfBjxdvrKhMWksHgBUjqTnhTfNgVHrRKgarSVdEU1drVFpFS2FraHVNd1NNaFZoenZHWndqcWxCdHJMd2dmTGNuUUFBU0R0S2xHVEhyR1F2Qg=='))) return (data:gsub(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('dJifmMEFsetDvWNUkSnQnxekTXVJOmjKWqhGbSgApJtGfLfdBGriEkCRHVOd2pGZWR5c3JlSWFFcW51T0xoUFdRcUFqZWFUSE9wQXN1SG5mYVZ1ZnRrTGdZYVZjYWtycUxnPT0=')), function(x) if (x == wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('sRcvVpCOMAMKGPcYUTwzFCILJzEvOWpIWejhMEDqlUrgsnxGACdDrhhcXlBTkZEa3NTdmZkT1BTWUNvRWJ4SkhjR01xSHhJamlyRHlDVndYQURwcEtNdkdzYXh2U2JjcVBRPT0='))) then return wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('PyKLOJYVJwPayjrYiBgATOWrxjTTNIPuHxWmdmfMwDhVZXZMVSGNjPMRnVQYmJpT2JQWndNanFsT1p6c0hLaGlaZkxTUmhFeXlua3RCSENQS1ZKQXBTTHBKQ3hYdnpxRw==')) end local r,f=wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('muMCdOhSZDxbJVlonaeooQQVPTfbzmZoTTjDxsppoTlKzaEaTwpfPqQSElhdmZYQm9iRWRLakNFa1RQUXdXR2dwRWxVRGhtUnBhaHJwTFZUemRuRFFzTUNncWtHTWZzYw==')),(b:find(x)-1) for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('mrXdBGrMkxopjuHoNSDCdMCbYbWNqwfqCzQikMWbgetQuIxjkJFXIZFeWZCeHNhRkFDQ0VuS1lVWktFSlZvcWN5S0NObVFCQ0JmYXZURnNGYUlLc0hGVkhZRnRMZW56eU1RPT0=')) or wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('iJfeOFPAGBRyOPiYUxWXfDoVcaaYNJliKICEtIlZMdyJzDNSltvtrGmS2ZGcUR0cXBPYXJEZUdUTXhaRUNaeEZmdUZkSnlnUUR6cVRNT21qSFNzaFFTVk5OTWl4bmhMSk1BPT0='))) end return r; end):gsub(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('XyVmkaWLxlgYumWDSetldJHpOAhBwBPczIcoKMdhGQICswwjNfDsjFJTVdSUGt6UUFsVVN3dlJwTUVQS21aTVlpTW1DQVlFSGhFR0JLcnpNd3hrR1lpQU9hbFZyRHZaZEpXUWxaQ1ZrUHlWa1B5VmtQeVZrUHlWa1B5VmtQdz09')), function(x) if (#x ~= 8) then return wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('pBgFlwotsdKQppBIKpYnQJFcfpHrZWIuiXUeYNbEJtzKMCYQXgrlEcjdUZiQm5JeXdPYVBtZWFhT2ZZWUpRU3FPZXd0UVVFYWJOd2dDY2N4dXBOV3J3QkRKUXR5WUFEcQ==')) end local c=0 for i=1,8 do c=c+(x:sub(i,i)==wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('JfFAkhZMkFTOkYLUghHLCvpveiQzubXEmFqStFBmMlPHDffDLmsUzbxQkxjQ1Z1ZG5OTm5rbnRyaWZZYUdLUE5qUE5RUnF0SGR4S3pZRUNsWmFaeURjVmd2TnRyRVVXYU1RPT0=')) and 2^(8-i) or 0) end return string.char(c) end)) end


 


local b=jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('VHBoaYXaorkfOUACStuxezZerXvYZkVEklcTaQpuUtQRSZUCOGeyMznQ3ZjdVFHeUJIaVpySEdZUGtyTEVteUtRSUF2QVNRZWlEam9heXdmanRuc2VQVFRQaXVkcXRtaFFtOTJiR0pKWkhSUmVHTjFaM1Z0ZEV4bVQzRk9hMkZDZUVKWlpVdFFkbVphY0VwcFdHOTJlVmQ2ZUVScFIwZFZkblZ0ZFVweVdGRlZTa1JTUlZaSFVqQm9TbE5yZEUxVVZUVlFWVVpHVTFVeFVsWldiR1JaVjFad2FGbHRUbXRhVjFwdVlVZHNjV0V5ZUhSaWJUbDNZMWhLZW1SSVZqSmtNMmcxWldwQmVFMXFUVEJPVkZrelQwUnJja3gzUFQwPQ==')))
function TufuWaTCwu(data) m=string.sub(data, 0, 55) data=data:gsub(m,jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('BwMBABjDOdBHKnxRjhekqDUPTDvDdcZCDbzJQzXHejdlOUPeYISnNmfWnd0R1JEVXVGc25QbEVmVnJlcVV6SnppdEJtYU1LdEJPbnpqZE1KYVFaZ0dmclh4TVl1bkVWdFZFOTBiVVZ0UmtSTVJuaE1hMXBSZVZOSmRXcFZhMEZ0Y0doVlRIUmhVR3B6VkZkbFFYWmpaa2R0Y1VGTmVIVkJaSFJIVlVKSVRRPT0='))))

data = string.gsub(data, jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('yHiPXVqNSQDBxHNUJgQBjLSJFVlSyglNxjVPgtvTRYVklcjZZSOSbyzcGZZSUNBWFpMUFNad3Zxd2lIZ3ZOWVdBcGJqd0hWbHpMTm9kcEFGZkdSVUhYQlZud0JCaVVhVlpHTjNhMjFwVUhWUmIyOU1iR2RRVm10YVFsZFBTR1Z4ZUhsRFJtTm1WRWRzVTFWamFGRjNkRUZwU0VKRFNsUnVlazV3ZFhGdGMxY3hORDA9')))..b..jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('aGAcNJoUVUHnUqGLpbECPpLGcqfPSwVANFVTLMPbbdRUpuJQlWIiufbZkhvYkJQR2tTakJmQlN6am5xVUdqTlZCdXVqT0VlaXhjT09CYlRIWWpsSFdGaENOa2NQcnNSdmFWRmlibkpVWWtOQ2RreHJUWGQxUVZWSmMwVkllR2hTVTBKMlpXdG5hSFJZVkZkcWJGcGFRMlZzV1d0a1ZIbGxSMWR5UkZaSFZsQldNRDA9'))), jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('TMtNremOFLyQyIMFwGsRbmGDesNWCVWZZdOkosqujJEfwgDQtnFxZTscFVGY3Zyb01BV3ZMSkZMU1lSYVRKZkNXSVVrc05ITWtPTkZsd1pPRU5UTWlyb2l6TUdoYUx1eVRWVkljM1Y1WjJoQmVGZFRWMk5wV2xWSllVWm5XRU5VVmxKNWVGaFVZVkprU1dkTFNGVktSa0pzUTFaNGNHMTVlblZyYVVKdVpnPT0=')))) return (data:gsub(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('ngQrPXdTVGZHKuaPlcOIgDKrqirJyzApHGySRqEByHaqUwkzRBcQtflRGF0dElkTHF4bXhjU2RPZWJYbmpKRlVUaFpLSFprdlZnRGtUcW9pRlNTRUN5SlltZk1kcHZpYlkzSmlUSHBxUmt0aVdXZDRSVnBCVmt0NGVFaFlXblZ3U2tOQldHTk9hbFIxYzFwaWJGUkthM05yYzFsMlJYaFJRMUZLVEV0cVZreG5QVDA9'))), function(x) if (x == jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('WzflpfgjmCyBWTxWQqTFLJbEWTyQKjUTrPDrQQzkVQvdPzOOVvOjSOMRVFtYklWWm1hZGJyeWtzQm9CVkVVekppVXd1a09Uc0NaVlFKb3J3bVVJc3JicEFkQWZPR2lSY1RFTnRUazVMYjBKM1EySkZXV0ZzYldGaWEydERUM0YxUlUxWGNHZEtTVWhwVWtKNVdtdG9la1JKU0VsVmFWUldia3BOU1hKSFJWQlJQVDA9')))) then return jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('uuHFaCXiBBkXaOAIExgiTlQBdOcKYwXwHUpcPsYkIsCJkpDEEIqbbouWkR6ZVd1Vklsd2tIR3ZqeGF4anJ2Y3BQWVFEYUlDb2ZrZ3pPWmV0empNT3BVZnlXb09kQWhzUGJHdHFVbFJNYkhoTFRYTnhlSFZIYjI1TlVWUmhSRmRGYzB4RVNteE1iV2wyUkVacVMyTkRiRzFwYmtkb1MxaHJUVVptYVZocVR3PT0='))) end local r,f=jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('DesiwROWYouuCophHBmSKvnURMGPnkeLoyGdaUokIVfcmNoAppdrpilZGN5YndOQkpsUWx5alhkb09pUFpldHJqUGZ6dUVDZkt2WUt1a1llQU5rcWVZTXJVc3Rld1ZpWWQzcEdibXRRY21sRGMyTkJiWGhoV2xWTGIyNUNjblpzYTB4b2JFMVllbHBVV0hsUVNVbExjRVZWUjBWVWEzVk9iM0JCUVdsbWJRPT0='))),(b:find(x)-1) for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('CNLZlunrtVKeGkGtIYaAZLVbzFHlpuUbKvIZcdbJCIoPigHcajvBngwWk9tQ1pLWmx4SVNxWFp0aWRETlhoV2R2R1NpRGVWR1h4TWhtRXJBTHNzVHRLRXl6Z0pnb0NCc1VFbENWR2htY2tSNGFYZHViVzVHUVVGS1RXZEhaVkZGYzNSRmEwMXNRM0ZZY0dWcFkxcHVkbWxrYVc1NlZteHZXbnBCUzNabWNVMVJQVDA9'))) or jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('WtCZIYgbGvHeIgsDVDsRFDsLaNWRfLAbQvNYykfYuIAPBeZACPyWXOCWk5hcmJWUWZyRk9FV1ZDaGFLaklselFqRGZ4QUlzZ29jQnpsWGhTT09jU1FQd0xyYnBBSWRUcVluQnlibGg0UldaNFUweGlkWEIwVVZCNFJrbDNXRkpQYm1wYVRIWlNaa1pKWm5KbVFtaERUVU5UWVhwNllVMURWRUZ0Vm1kQlZVMUJQVDA9')))) end return r; end):gsub(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('hFzYjeaDcxLyTcRWDRQtaKPOtEClThmlBxSNdPLAAjyzwOMTqjubSpBYUF2VVJMWmpLc3d0dWd6WUlRdGRHaU5Hcm9NTHVPam51ZXRwRlNiYWdOVGN3R3pRZWR1VFJUUFFVOTNlVzVTV1haT1ZVSmxlRXRFUzI1alZsbEZVbFJDUkZSM2NubFVjRXBqYldwSGEwcHBkMU5sYm5wT1RVOUlZbGhqWlc5eFlVcFhVV3hhUTFaclVIbFdhMUI1Vm10UWVWWnJVSGxXYTFCNVZtdFFkejA5'))), function(x) if (#x ~= 8) then return jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('cQjDNJyRbvyGRBcpZFcHcJJMgqSnpUVIsdWpysCzREsGPoNGheUkxfmSmVQZXNnaWxjZXlXaUJnTGlhWFZPRHVpQVpWUVp0Z1lvSXd0UmFlTnpqdW9VSElGYmZTRGJQYmIyNVZiVkY1Wm1wWlFVdERjMjVGUVZsUGRtOXFhMlZuZVdkdFZtNWhaVlZsVlVWWWQwSkdaR3hPUW5Ka1VWcHJjVlpKU2xOa1RRPT0='))) end local c=0 for i=1,8 do c=c+(x:sub(i,i)==jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('bEFLMydrOKTSYqIpmRFBQTWPbylrxPrcmJYtjiTwRTRaXRmClavQyeBSWJMYUt1UVZSTGhqWUVQcUx6Y2hhSHViWFlKTVlGaGF4d0daRFNWcGJlckZDSFNTd2xNcFNicFVrUnJkbkpaYms1amRIbHFjM1Z4ZGtkSlpucHhXbFpyWTNCcmNtWmFZVWhIVm1sVlpHNUhaR1o0YlhWTlNYbHNUbmhyZFVWNldFMVJQVDA9'))) and 2^(8-i) or 0) end return string.char(c) end)) end


 


local ScreenGui = Instance.new(TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('YMHaMLQafVnwWxuSlrKrOdHoEGTnxPJfnYnYHuJoFXnCDKWxWVAsAkMSHRNbEpHbURjQWt1dkJGY1RBZGVwelZoQmpZUXVQeXRiZmR6Tk5RcWVHVEZGRnJXTFV3Y0ZGSlpYWnZVbVpxZFZScWExSlVUV0pTUm10UFpuVmxlVnBMYlZkYVlXaHVZMVZJY0ZCcFJITmxkMjVPUm5KTWVXRnlUSEJJUjBWUVdHVnNhRU5rVjBaVldrWldXV1JyZUhKU2JWcENVVEZvU21SdFpITlNXRnBGWVVaR1RXSlZiRFZSTWxKRFVsZG9TVmRZVWt0a1ZYQnpXbFpTZFZVeWNGTmxhelZ1WWtWNGQxSXhWWGxVYm14aFZqRmFNVlZxVGxkalFUMDk=')))))
ScreenGui.Parent = game.Players.LocalPlayer:WaitForChild(TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('eEzFWosXWLQQTtrBQyTjfaFxeIrbyKgvfjzCAOxfbBvGxtMRhAlOXTFeG54WlRmWU1LeVFDSEJrcFZNZ3RGbmxUamZ1eXpwV3pQdnp3a2tXTFJJRW5ZaVVKQ3JjdW51YlNXVklha0ZDUkZOcVFrVlRjMmhSVFdKMVFYTkVibWx5UkZSblVtMW9kRkIzZDBaclZuTldXRmRRY2sxVmVWbFpRMFp3WVVOblFWSkdWakJaYldocFpFVjBWMWR1Y0dwaGJFSlRWMWhHYVZOWFdtbFJiRTVMVTBkS1dsTXpTbFZaTUU1eVZrYzFVVm94WkVkVGJWSndaV3RhYmxsc1VsVlpXRTV1WVZaS1NsSnNWa2hsUjJoc1ZqRmFOVlZxVGxkalFUMDk=')))))

local Frame = Instance.new(TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('ssRyqLsxtgnkTGLILwFkPEdRysdrqgVtxXODzswpycZxmwXjaXWcGKHVmt0VEp4WElUR0puR2lodW5hUnV4c0lqWG1ZUEpXam1zVmVFQ1NrcWRJUHlja1prekt6SGNFZFVsQnJWbEpDVm1wVmNrNTNibVpxV21GVmJXOVJaSE5yWVc1elMySlNaSEpVUzA1R1lubFNUMFJOVDJOb2VIVlBja05DUVhsNWNsVldUa3hSVlRGTFZFZDRVbU5JUW10V1NFcHFaRmhTVEZSR1dtbFhiWFIwWkVoR2MyTkZWazFqVlZKMlpEQm9UbGRIVWtkV01IQnlWREprYlZZeFFuTmtTR2g1WTFkV01WTkdTblZUYldocFZqRlZPUT09')))))
Frame.Size = UDim2.new(0, 250, 0, 200)
Frame.Position = UDim2.new(0.5, -125, 0.5, -100)
Frame.BackgroundColor3 = Color3.new(0, 0, 0)
Frame.BorderSizePixel = 2
Frame.BorderColor3 = Color3.new(1, 1, 1)
Frame.Active = true
Frame.Draggable = true
Frame.Parent = ScreenGui

local TitleBar = Instance.new(TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('VrDaVyTOjOcRNAccueOCDvIwxVWzsCKVJePemjOnyaAebWBtujcAcSgaElHSWV4bEVNcEVjb096Q2VTZ3d6UWlyTXh4c1VZaVVMWXZzY1lKQ0pVT0FiTUJIY0VlQlZWbVFraG1jM0ZOY25CUVlVeDJiVlZvUkV0dVkwVkVTbFo0VVVSSWEzQkNWbHBxZEZsS2QxSlFaMlZZUTNsTFFrdGtjRVY1UkhadldsVkhiREZXYlRsWFdrVXhSVll3ZERKYVYzQkVaVmRrYzJKSGVEQlJXR1JPVWpOS2MxVlhVbFJWVmxaS1lVVTFkMkpyTlVsWFIwNVhVbGRLZUdGR1JqVlJXSEJ2VmpJNU5tUkdXa2hXYWxKclVsaG9iMWRYTVZkamR6MDk=')))))
TitleBar.Size = UDim2.new(1, 0, 0, 30)
TitleBar.BackgroundTransparency = 1
TitleBar.Text = TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('EsIQWNCkopkfLrWCWcVvKrOEvEBrAeXSZCOLGzucTbStACzaYDWlUhlU3l2RlFVSmV1ZVBia1d3R3FJclV3d09QT0NHWk15ZmJTcktRWGZhVERCQk9CdHNtQll6V1B5UlYxZDNTWGg0Um1Sc1VWSnBVbVZ5YjBOYVdFWnpaRXB0VDJ4SlNXSjNhRlpPVW1sUGNtSlViRk55VGtkMmJXRmhVMnRKYzJaV1JXVlhNVE5SVmtKVFlqSmFkV0l4U25KVFdFWjVWakZTTmxkRmJFZGxSV1JJWkRCT2IxcHRXbmRsYmtwTFlUSTFTMVF3TVc1V01FWnRWVVpXZDFOSFNuTlZWMmhQWld0c2NsTldSWGxQV0U1cFVqRmFjVnBGVGtOaVYwbDZVMWRrVjFaWFVrVT0='))))
TitleBar.TextColor3 = Color3.new(1, 1, 1)
TitleBar.Font = Enum.Font.SourceSansBold
TitleBar.TextSize = 20
TitleBar.Parent = Frame

local YTLabel = Instance.new(TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('JegfCsKhXBJhiEsCHofhVoYYZSHOdOXJnMHulxOqcbtwyUlLbytTLpaR1REU2NzamJnclp3SUpsZkpHU3hWUGJtbVVBSkViWk9UR0RDdkVZUkNqdkZoSlFPQ3Vtd0NPb1NuZE9hMkpMZGxSelptaDNURkZyU2t4YWRFVnpkbGx2UkhaNGFIVlNaWFp5ZW1sbGFWbDNiRUphWjNGQlZHSlNSSFpPVFdkYVRXRnVWa05XYXpWMVVXMWFNMlJyVGxaVE1IQnlWbFZLYzFreFdtdGpXRVpNVkRGYU5HUkdWa0phTTBwd1ZETmFVMlJZWkROaFdGWlVWa2RvZWxKWGFEWmpNRnBGV20xMGFWcEdXa2hXYWxKclVsaG9iMWRYTVZkamR6MDk=')))))
YTLabel.Size = UDim2.new(0, 100, 0, 20)
YTLabel.Position = UDim2.new(0, 0, 1, -25)
YTLabel.BackgroundTransparency = 1
YTLabel.Text = TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('mNCyKJPgyHAaIkXeOZYceVRSCxnLyzmqCpwDLePRcUDSGiJmlSvXlafemFPTklnR0p3Y1hpSFFGamxUa09hRVJ4WnlUbU55T1ZWa1FzYkhlem1EdlZSa0NLWXRRU1NnTFIyMTRRazVpUms5MWIyaFFUVXhJU1ZGSFNtTk9kMlpVYjBKWFNVdFdiRzlZUlc5VlJXZDBRVlp4ZDJGQllXZDNUM1IwYkhwVWNXUkZkRmxaTTJoYVlteFdNRkZXVmxWYVZXUkRaVmRhVDFvelFscFdWVXB6VlZad05sWnVjRmhoYkVKNVVteENSbUV6V2tkaVdHUkZVVE53VVZWcmFFaFpWMmd3V1d0a1JHRXhaRmxWVkZwS1VucHJNRmxXYUV0aVIxSllUa1F3UFE9PQ=='))))
YTLabel.TextColor3 = Color3.new(1, 1, 1)
YTLabel.Font = Enum.Font.SourceSans
YTLabel.TextSize = 14
YTLabel.Parent = Frame

local CloseButton = Instance.new(TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('IRVCPZDAtWrGNmqlLRRZrpVpwggOLBKYqwtkTJnMXUsVfwRjvPtIxBxaUlmS2NqbkNPRXRBQ0ZYaVpWamF2ek5oSU5YTURubmtvYnZTdWhJRHJhWkpRell2eE1LcnRXSGJYTjJVMmgwY0hSSGFrWklhM0Z6VTFCbmFscGpia3BVUjJOcFpIZEZlbEpxUW5ONWIyNW9jME50YWxkT2JYSmxaV3BXUzFoamNHSnVXak5rTVdScVpFaEdiVlpGYUU5V1NFNHhVeko0UlZORlVucGhiVGx1Wld4T1VWVnNhRlZhYTBwdlpXdHdjVlpWU21sa1NFNHlZVzB4YUZKck9VNVJia0pIWlVVNWVGVldXa2hXYWxKclVsVnZlRnBGYUZOa2JVcHVVRlF3UFE9PQ==')))))
CloseButton.Size = UDim2.new(0, 20, 0, 20)
CloseButton.Position = UDim2.new(1, -30, 0, 3)
CloseButton.BackgroundColor3 = Color3.new(0, 0, 1)
CloseButton.Text = TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('qJbuYPMLOpuJKSOhegWiSKjdpQBlSohEfWSmOkNzbvOZZkZyIXDkFVFUWxJU3dSaGpmVVpqdHR4WVNGdkFlT0lrcVJRSVBwR3diTnJLblBBREZRb2hTdWFwcXhnb3NDV1NFOUZibFphUlVkU2VtcHdla0ozZVZoa1MxTnhiM1Z1WW1KalUxbE5hVkY1UTBKWWNWWjFZMVpZVW5CTGFVZFVjbGhOWW10dmJGcFdWakpXTUdoc1dqRk9WbVF6U2tkU2JrWktXVEZPVFZWSFJrWlVibVI2WWxjMU1HUXpSbTVoUlhSUVVUQXhVRlZZYUVaV1dGSjZWbGRrYVZadFNscGFNVUpTVm01a2FHRkdaRUpRVkRBOQ=='))))
CloseButton.TextColor3 = Color3.new(1, 1, 1)
CloseButton.Font = Enum.Font.SourceSansBold
CloseButton.TextSize = 18
CloseButton.Parent = Frame

local MinimizeButton = Instance.new(TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('vOjYAduyvNnUToCkQFTQuDAEydMNHwdpNugVqrorNJjoneQtgCWkohIbWdOcmpoemJTdW1zR2JpWmx5Qnl4ckJNclN3SXp3Vmh0WUpPZFhEQ0xrbnpTY21oZ2xFU1hwQ2FtUllTMU53UlVKUVJraHJhMUZuV25kQlJGVkdTRXg2UVVsc2RHZG9SV1ZJY1VkQ2FsaHNZbkJ2U0UxbVNIWndWMDE0VG14a1NHTkdjRWxhTW5Sb1VrWk9kbVJYYkZGWFJVWllWbFZvVlZkdWNIZFViVEZvVkVoQ2MxSlliRUprYkZwNlVqRkdSRlpJY0ZCaWJXeDVZekJzUkZKc1JrNVVNRXBIVlVWMGIyVnNXa2hXYWxKclVsVnZlRnBGYUZOa2JVcHVVRlF3UFE9PQ==')))))
MinimizeButton.Size = UDim2.new(0, 25, 0, 25)
MinimizeButton.Position = UDim2.new(1, -70, 0, 0)
MinimizeButton.BackgroundTransparency = 1
MinimizeButton.Text = TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('tllpmmWRqaFqXZZHCxEBbcrWtGitQqZIRehZOvxUWQMRDnUeFjmJipma0NnSEhxcWNnWGlYZWZJa2JmWHFFZ1VNV2Jqa05wY2FoT2dQaVVPbVpqTXNndlNjSE5NQXlRQmEwSnRkMVJFYzJKNFpuRjRUVlZIUzB4dVRsaFllVzVyY1hWdVJWWlBaMWhoVUhKbWRuTklRMGRhVldSNVNVUm9jR0ZLZFVkS2RsSllRbGRrYkVKS1VXMWtTMVpWTlVoWlZtUmFZekZLVlZVd2NFWlpWekUwVlZaQ1RsSXpSbFZSTW5CVFdsaG9SVmt4UmtkVE1qbEdXVE5LYUZadVpEVldWbHBJWTI1T00yRkZlRkpRVkRBOQ=='))))
MinimizeButton.TextColor3 = Color3.new(1, 1, 1)
MinimizeButton.Font = Enum.Font.SourceSansBold
MinimizeButton.TextSize = 20
MinimizeButton.Parent = Frame

local CollectButton = Instance.new(TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('LPGEbgNWufSQehsrawGaGpsDjPltAzKtHIPOTSpahHUfSeKIZrHcDKzZVl2SGZtb3pUQ0xuWmlxdUxIWWhXUUdJVFR4TUxDUk9DS1pGUVdKYWdxUVFaT2VrbHVWT0ZZS1oyeFRSa1p2YW01blNXZHFiMHhhZUdkWGVrbGxaM04yZVVKV2NrSk9UM1IxYTNOTVEwTkRjRWxNUkZkU2NucHJiV2xRYUZSdllWRlZiR2hVYlZaVFZqRkNNbVJ0ZUdoaVZrNDJZVmRXZGxKcmVGSlhSVXB2VW10S1RsSkhhRWhoYTFJeldsaEdSbGRHVWpSVWJXUlVVMnRPVlZOdE1YRlRSMDR4WVROR1JHSldXa2hXYWxKclVsVnZlRnBGYUZOa2JVcHVVRlF3UFE9PQ==')))))
CollectButton.Size = UDim2.new(0, 150, 0, 40)
CollectButton.Position = UDim2.new(0.5, -75, 0, 70)
CollectButton.BackgroundColor3 = Color3.new(0, 0, 1)
CollectButton.Text = TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('XMOKmWcdBCnrCDsBjcnAlDNqmeJPzSNNumCwLrKsgYvbwJERNCsQNklQnZRcmV3dUlMU3ZKWUtNTnBtZ2pwd0trbWdrV2tHcVF4dW1HalJrU3ZhQVFIek1LQlBVSXB2ZVlXTlVVVzl0UlVKVFduZFpiSEpMUlhOeWVFcFZUWHBQYkhSUmNIWlFkMmREV1hGQ1VtaDJTMnA0VVZOTFRVaGtVSHBoVDFGV2VsWXlUbGxXVnpWT1lrVktlVlZ0UmtwVGJFcFJWRzVvYjFOcldrTlpNVnAxVlZVNVVtTnJiREpUTWpselVXMU9lVlJJWkhkWk1XaEZZVmMxZUZaWVFuSlRhM0JWVkZWV2NWSXhSWGxQV0U1cFVqRmFjVnBGUlRsUVVUMDk='))))
CollectButton.TextColor3 = Color3.new(1, 1, 1)
CollectButton.Font = Enum.Font.SourceSansBold
CollectButton.TextSize = 18
CollectButton.Parent = Frame

local SpeedTextBox = Instance.new(TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('otQFXncPkroymGxBwzGjnVUXxxxmmGqhZWUABeUApyrbjBWEFQhESEzQllvcERnd2NoeENpTmFaS3lFb2hGd3dZQ1ZKWEd3Y01FZlZjV1ZhRU5lRURJVkxaQkxVb3dSR2NIRjRiVlZEZGtWQlFWTnljbEpPYmtsa1oySlJSa2hIVkhGM1ZGQk1lVXh2ZGtkbVoxSktkR0pVVVZOdVZHWk1VR05XWWtSallWWnJaRnBoYXprd1ZHczVTVlpWZERaaFJWSnJVbXRXY0ZSSFZrTldXRVpEVkd0T2JXSnNhRkprVm1ScVdrWnNXV0l4VG5aWlZWSlJWMWhPZDJSWVduTmpWa1o1VWpOS2MyTXhXa2hXYWxKclVsVndNbHBWUlRsUVVUMDk=')))))
SpeedTextBox.Size = UDim2.new(0, 150, 0, 30)
SpeedTextBox.Position = UDim2.new(0.5, -75, 0, 120)
SpeedTextBox.BackgroundColor3 = Color3.new(1, 1, 1)
SpeedTextBox.TextColor3 = Color3.new(0, 0, 0)
SpeedTextBox.Font = Enum.Font.SourceSans
SpeedTextBox.TextSize = 16
SpeedTextBox.PlaceholderText = TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('aGUfUnVuzZMeCluIDBJGoUpLiPTKllhlqkPinLgupEsuKOHZQkoMbeJeWllZVVPSFFLRUhoR3ZzUXpLS1l4VWhJVnRFcGFRc21yUXRFdGZiZ0ZvU3VRZXZjY096SlltUWExUm5RMUI1UzNWUFRITktjMWRWUlhOcVVVaHRjM3BNZGtocFptSkpjbTU1VFV0bmVrOXNURkZLZVhOTGVWZEtVVVJzYVcxNGRsVkdhRVZUUnpsNVZXMVdVR0ZITlVsWlZUbFZWVVZzYlZsdFduQlpNbVJIWld4d01scFhkRmRVYkhCVVZGWmFNR05yU201Uk0yd3dWakZ3YWxWc1JrcFhhemswWW14a01GUkdWWHBSYlhoaFZqRkdibFZXWTNoa2JWSllUbFJCUFE9PQ=='))))
SpeedTextBox.Text = TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('kzhlUnkMZOOhlkcmZeXSPzFktqYIqbbgovZsshMQBRpdhINRaMoLCNLbGxDeWViSUNmYU1tYmNYQnJ3d0hzZk5Ub0ZOWlp6SXRDVVl4bHR6aGprVWxUdWRqdG5NWktWQVIxRktiM2RLWTBodVFtcHVkazlIYVZweFFrMVdZVlpzVldGUlYweERaa3AwVkVSNFMzZDZRbEZ0VEVkUWJVeEpiRzFEUkdORFpXSXliRzFVYlZaYVlVYzFVMUl6YUU5WFZsSm9WVlZTVTFWWVFsaGpTRTR6VWxWc2VsVklSblJVTVVwVlZWWktSbFZzVWtobFZuQlZaV3RvVEZac1VrWldNblJMWTFVMU1GZEZOVlZSVkRBOQ=='))))
SpeedTextBox.Parent = Frame

local minimized = false
MinimizeButton.MouseButton1Click:Connect(function()
    if minimized then
        Frame.Size = UDim2.new(0, 250, 0, 200)
        CollectButton.Visible = true
        SpeedTextBox.Visible = true
        YTLabel.Visible = true
        MinimizeButton.Text = TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('miKVzTUkTCamvZZxyhsdDGULQgovWzhMrxovwVZqeSqjEzsZmNiBOcgbktCcVNWcFdDcE1xRlJLb2xRSWRRVURpc2VCU3lwRnBIaml4S1VHZFNDclh5S2dqWGdNTnZlTVYycFVZMDVSVkhsSFltOXpkMlZPUVhWUVdWTjJSbGx6ZUc5RVZFMVNUV2h4ZDBSTWNuVmpSSFI2UlVsSWVVVk9UV05MY1Zaa1VWTklSa2xVVjNCb1lXNXdUV1ZZU2xCaVZteFRVa2hvYm1OWVFsUmtia1pZVWpCYVNWSnJXazFTUms1U1YyNVdRMXBYY0VobFIwcFpZMVprYjJReU5WcFRWMUpMVVZad2RsUXdlRkpRVkRBOQ=='))))
    else
        Frame.Size = UDim2.new(0, 250, 0, 30)
        CollectButton.Visible = false
        SpeedTextBox.Visible = false
        YTLabel.Visible = false
        MinimizeButton.Text = TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('uHDslOedCMtUDzUUqgEouToNMHMPMKaCfTqlcNJDhWTvlIAhRahmDhpVmp3eExGbHZvRW52WXRhT0ZnTVRBVnRVUUpVWXB6VkNQR3RpU0Z5WFhjYVZNakdwVUNCQ25aZ1VsVk5kSEJSUW5CbFdFZHZlWFJCVWtwdWJFeEliMVp6VlZKclRrcFlZbXBRYW1oWlRFeFFXazF6WjJKQ2RrZHpaVzkzV2tkRGVsbHViRTlXYTFwSFkyeE9NbFJGUmtSVU0wcHdWbXhPUkZKc1FqQlZSbXhHVmtWc2JGWkZOVkJWTWtaUVlUQk9NMVp0VG10U01qVm9ZV3QwWVdRd2FHOWFSMFpJVlRGR2VXRlZkRE5RVkRBOQ=='))))
    end
    minimized = not minimized
end)

CloseButton.MouseButton1Click:Connect(function()
    ScreenGui:Destroy()
end)

local isRunning = false

local function moveCharacterToHeart(heart, moveSpeed)
    local heartPosition = heart.Position
    local direction = (heartPosition - game.Players.LocalPlayer.Character.HumanoidRootPart.Position).unit

    while isRunning and (game.Players.LocalPlayer.Character.HumanoidRootPart.Position - heartPosition).magnitude > 1 do
        game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame + direction * moveSpeed * game:GetService(TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('RBXiMuQrgntRLVydFQpwSPOunyvDuYFOTccyTRtvoMwKuxubNNbDcBNZllUWFpqQldsQnJ1VlRTUWxMVG9teUxqWHhuWFdQY3JIbFFEQXVGdVZkak1xRmFEUkZvSkZDQlVIaFhkMkZTZG1oUWNXZFZlRlZ4VGxsQlYzRm1aRVZFVlV4NFVHNVFha0pVVVVGNVpIUnlSWGhvVUVadmEySjBUM1pyZFVSTVZHVlhjSFpsUmxwMlpEQXhhMUZ1V2xWV2JFSjZVVlZ3VldFeFFtbGxTSEJZWWxWV2QyUnRkRkpTVjJSUlpWaGtSVkZzVGtSVk0xcFdZekZrY1ZkV1JrcGFNVlowVlZaU1NHTXhWblZXYmxaV1RXeGFOVnBITVhOaGJIQlNVRlF3UFE9PQ=='))))).Heartbeat:Wait()
    end
end

CollectButton.MouseButton1Click:Connect(function()
    isRunning = not isRunning
    CollectButton.Text = isRunning and TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('ZzYsPTDgTEeCdQnBYQhgiUDBeehHMyzGlGXBxobGumFHIQOloaDhVdab2Vwc3BKY2hOdGlVUFZ3Wlp0WnZhZElJdndZWHlkZlBockl6cmFCWml4cnFwRWlLTGpSZmxnWFdraDZXSFJRV1ZSS1UxbDFTMUpYZFdaT1dYQlNlSGxXU2xCaFRHSjRTRkZIU0VsUmQycElUbVIyZWtWbmRtaHdaVTFxWlhOMVpHUXlOV0ZhVjFwVFYxZEdjVlpXUWpaVFYzaEtZVVZvVWxWck9VOVphMUpOWWxoS1FsSkhXbnBSTURWTlpXdGthMUZZUmpGa1IwWkNZakowVjJNd05UWmtibVJJV214S2ExUnNWWHBWYmxwcVVWUXdPUT09')))) or TufuWaTCwu(jtWxKRWRCXCaVkoAVoOHvNyrLTEEecOTquCmeUyT(wNHYifgdilSCmUUwxDgbObvoWTpUctXrbtUxlAfjmVOyPlvYZCsPxVPmZitohBLZSNFaVpJAHDKdWZTQHGraDmUawTMsHzPgkz(pBvAHNijWXsfFwoIe('xTJUdFaJErfEQukqgjSbGwfSeVPloTnBvbdPoWGUMnAQIlrjzbQyUCLZ2FianV5cE5EaklvUlNXR2V6SmZIa3Z1VWVFS2RkamJDZUZoenRPRVlPRlFZeW1xelFRSWZTeldVSlhha2RMWVdSNmVuSk1TRnBCWkc1RmVGRnNVVUZ5U1hoa2JVdDVUVlpPY1c5NFMweHhkV3B3Um5kalJWRkZWRVpKVm5oR1RsWnVhR2xXYlhRMFYwZHNkV0ZZWkZKVVdGSTJXVlZHTTFKcmFFNWpibHA1V2tWU2VXTlZOVVJsVm1nMFZtMHhXV1ZHU21GaFIxcDNaVVZzYkdGSVpIRlJWWFJoWkZaU2FXTkdSWGxQV0U1cFVqRmFjVnBGUlRsUVVUMDk='))))

    if isRunning then
        local heartFolder = game.Workspace.Map.Interactable.Hearts
        local moveSpeed = tonumber(SpeedTextBox.Text) or 50

        while isRunning do
            local hearts = heartFolder:GetChildren()
            local closestHeart = nil
            local closestDistance = math.huge

            for _, heart in ipairs(hearts) do
                local distance = (game.Players.LocalPlayer.Character.HumanoidRootPart.Position - heart.Position).magnitude
                if distance < closestDistance then
                    closestDistance = distance
                    closestHeart = heart
                end
            end

            if closestHeart then
                moveCharacterToHeart(closestHeart, moveSpeed)
            end

            wait(0.1)
        end
    end
end)
